### ISSUE TITLE
ql:quickload :adopt pulls old version

### ISSUE THREAD

**Issue by dcamper** [sjl/adopt#3]
It looks like version 1.0.0 of adopt is pulled in by quickload.  Can quicklisp be updated?

Thanks!

**Comment by sjl** [comment]
The `quicklisp-projects` entry is pointing at the proper repo: https://github.com/quicklisp/quicklisp-projects/blob/master/projects/adopt/source.txt

I just updated my quicklisp dist and it pulls versions 1.1.1 for me, which is correct.  Are you sure you've updated your quicklisp dist via `(ql:update-all-dists)` and/or don't have an old version of Adopt in your `local-projects`?

**Comment by dcamper** [comment]
Ha!  I thought I had updated my quicklisp distributions but I had utterly failed to do so.

My apologies for the wasted bandwidth!

**Comment by sjl** [comment]
No worries, it was quick to verify.
